name: Generic issue template
description: For detailing generic/uncategorized issues in Xclim

body:
  - type: textarea
    id: generic-issue
    attributes:
      label: Generic Issue
      description: Please fill in the following information fields as needed.
      value: |
        * Raven version:
        * Operating System:

        ### Description
        <!--Describe what you were trying to get done.
        Tell us what happened, what went wrong, and what you expected to happen.-->

        ### What I Did
        <!--Paste the command(s) you ran and the output.
        If there was a crash, please include the traceback below.-->
        ```
        $ raven --foo bar
        ```

        ### What I Received
        <!--Paste the output or the stack trace of the problem you experienced here.-->
        ```
        Exception occurred
        Math error: Attempted to divide by Zero
        ```
