/*----------------------------------------------------------------
  Raven Library Source Code
  Copyright (c) 2008-2026 the Raven Development Team
  ----------------------------------------------------------------*/

// The Basic Model Interface (BMI)  class for Raven.
// 
// ================================================================
// Currently exposes for both input and output:
//   All state variables (nHRUs)
//   All forcing functions (nHRUs)
//   Streamflow/outflow (nSubBasins)
//   Reservoir stage (nSubBasins)
// ================================================================

#ifndef BMI_RAVEN
#define BMI_RAVEN

#include "BMI.h"
#include "Model.h"

const int GRID_SUBBASIN=1;
const int GRID_HRU     =0;

struct rvn_var_data
{
  diagnostic   type;         //forcing vs state var, etc (from custom output)
  string       name;         //e.g., SOIL[0] or RAINFALL

  sv_type      sv_type;      //e.g., SOIL
  int          sv_layer_ind; //
  forcing_type f_type;       //e.g., RAINFALL

  rvn_var_data(diagnostic typ, string nam)
  {
    type=typ;
    name=nam;
    sv_type=UNRECOGNIZED_SVTYPE;
    f_type=F_UNRECOGNIZED;
    sv_layer_ind=DOESNT_EXIST;
  }
};

class CRavenBMI : public bmixx::Bmi
{
  private:
    CModel     *pModel;
    optStruct   Options;
    time_struct tt;

    std::vector<rvn_var_data>  _input_vars;  //< input variable vector (Filled in initialize)
    std::vector<rvn_var_data>  _output_vars; //< output variable vector (Filled in initialize)

    double _duration;                        //< model duration [d] overridden in config file
    bool   _BMI_weather;                     //< true if forcings are generated by BMI coupler and no gauges or gridded data are needed

    void _ReadConfigFile(std::string config_file);
    void _CheckConfigVars(std::vector<rvn_var_data>  &vars);

    std::vector<char *> _SplitLineByWhitespace(std::string line);
    std::vector<std::string> _SplitLineByColon(std::string line);

    bool _IsValidSubBasinStateVariable(std::string var_name);

  public:
    CRavenBMI();
    ~CRavenBMI();

    // Model control functions.
    void Initialize(std::string config_file);
    void Update();
    void UpdateUntil(double time);
    void Finalize();

    // Model information functions.
    std::string GetComponentName();
    int GetInputItemCount();
    int GetOutputItemCount();
    std::vector<std::string> GetInputVarNames();
    std::vector<std::string> GetOutputVarNames();

    // Variable information functions
    int GetVarGrid(std::string name);
    std::string GetVarType(std::string name);
    std::string GetVarUnits(std::string name);
    int GetVarItemsize(std::string name);
    int GetVarNbytes(std::string name);
    std::string GetVarLocation(std::string name);

    double GetCurrentTime();
    double GetStartTime();
    double GetEndTime();
    std::string GetTimeUnits();
    double GetTimeStep();

    // Variable getters
    void GetValue(std::string name, void *dest);
    void *GetValuePtr(std::string name);
    void GetValueAtIndices(std::string name, void *dest, int *inds, int count);

    // Variable setters
    void SetValue(std::string name, void *src);
    void SetValueAtIndices(std::string name, int *inds, int count, void *src);

    // Grid information functions
    int GetGridRank(const int grid);
    int GetGridSize(const int grid);
    std::string GetGridType(const int grid);

    void GetGridShape(const int grid, int *shape);
    void GetGridSpacing(const int grid, double *spacing);
    void GetGridOrigin(const int grid, double *origin);

    void GetGridX(const int grid, double *x);
    void GetGridY(const int grid, double *y);
    void GetGridZ(const int grid, double *z);

    int  GetGridNodeCount(const int grid);
    int  GetGridEdgeCount(const int grid);
    int  GetGridFaceCount(const int grid);

    void GetGridEdgeNodes(const int grid, int *edge_nodes);
    void GetGridFaceEdges(const int grid, int *face_edges);
    void GetGridFaceNodes(const int grid, int *face_nodes);
    void GetGridNodesPerFace(const int grid, int *nodes_per_face);
};


////////////////////////////////////////////////////////////////////
/// NextGen expects two externalized functions, one to create a new
/// instance of the model and one to destroy/free an instance.
/// More: https://github.com/NOAA-OWP/ngen/blob/master/doc/BMI_MODELS.md#bmi-c-model-as-shared-library-1


#if defined(_WIN32)
	  #define LIB_API __declspec(dllexport) 
#elif defined(__GNUC__)
    #define LIB_API __attribute__((visibility("default")))
#else
    #define LIB_API
#endif
extern "C"
{
  //////////////////////////////////////////////////////////////////
  /// \brief Create a new instance of the model as expected by NextGen.
  /// \return A pointer to the newly allocated instance.
  //
	LIB_API CRavenBMI *bmi_model_create()
	{
		return new CRavenBMI();
	}

  //////////////////////////////////////////////////////////////////
  /// \brief Destroy/free an instance created with @see bmi_model_create
  /// \param ptr A pointer to the instance to be destroyed.
  //
	LIB_API void bmi_model_destroy(CRavenBMI *ptr)
	{
		delete ptr;
	}
}


#endif
