/*----------------------------------------------------------------
  Raven Library Source Code
  Copyright (c) 2008-2026 the Raven Development Team
 ----------------------------------------------------------------*/
#include "ResidualErrorModel.h"

double GaussRandom();

//////////////////////////////////////////////////////////////////
/// \brief Helper functions
//
double getPercentileVal(double *arr,const int N,double percentile)
{
  return arr[(int)(percentile*N)]; //TMP DEBUG - better interpolation needed
}
double BoxCoxTransform(const double &Q,const double &A,const double &lambda)
{
  if (lambda==0){return log(Q+A);} 
  else          {return (pow(Q+A,lambda)-1.0)/lambda;}
}
double InvBoxCoxTransform(const double eta,const double &Q,const double &A,const double &lambda)
//inverts eta = box(Q)-box(Qsim), not box(Qsim)
{
  if (lambda==0){return exp(eta)*(Q+A)-A;} 
  else          {return pow(lambda*eta+pow(Q+A,lambda),1.0/lambda)-A;}
}
//////////////////////////////////////////////////////////////////
/// \brief calculate Reliability of ensemble of size M
//
double Reliability(const double *obs, double **sim, const int N, const int M)
{
  /*obs.pval = calc.obs.pval(obs=obs,pred.reps=pred.reps)
  pval_sort = sort(obs.pval, index.return = T)
  y = pval_sort$x

  i = seq(1:N)
  PP = i/(N + 1);
  plotpoints = qqplot(PP, y, plot.it = F)
  alpha.prime = mean(abs(plotpoints$y - plotpoints$x))

  return 2 * alpha.prime;*/
  return ALMOST_INF;
}
//////////////////////////////////////////////////////////////////
/// \brief calculate Sharpness of ensemble of size M
//
double Sharpness(const double *obs, double **sim, const int N, const int M)
{ //Generated by Microsoft Copilot
  double sharpness = 0.0;
  int nObs=0;
  for (int n = 0; n < N; n++)
  {
    if(obs[n]!=RAV_BLANK_DATA) {
      // Ensemble mean
      double mean = 0.0;
      for (int m = 0; m < M; ++m){mean += sim[m][n];}
      mean /= static_cast<double>(M);

      // Sample standard deviation
      double variance = 0.0;
      double d;
      for (int  m = 0; m < M; ++m)
      {
        d = sim[m][n] - mean;
        variance += d * d;
      }
      variance /= static_cast<double>(M - 1);
      sharpness += sqrt(variance);
      nObs++;
    }
  }

  return sharpness / static_cast<double>(nObs);
}
//////////////////////////////////////////////////////////////////
/// \brief calculate CRPS of ensemble of size M
//
double CRPS(const double *obs, double **sim, const int N, const int M)
{ //Generated by Microsoft Copilot and revised
  double meanCRPS = 0.0;
  double term1,term2;
  int nObs=0;
  for (int n = 0; n < N; n++)
  {
    if (obs[n]!=RAV_BLANK_DATA){
      term1 = term2 = 0.0;
      for (int  i = 0; i < M; i++){
        term1 += fabs(sim[i][n] - obs[n]);
        for (int j = 0; j < M; j++){
          term2 += fabs(sim[i][n] - sim[j][n]);
        }
      }
      term1 /= static_cast<double>(M);
      term2 /= (2.0 * M * M);

      meanCRPS += (term1 - term2);
      nObs++;
    }
  }
  return meanCRPS / static_cast<double>(nObs);
}
//////////////////////////////////////////////////////////////////
/// \brief Residual error model constructor
//
CResidualErrorModel::CResidualErrorModel()
{
  _meanType=MEAN_CONSTANT;
  _pQ95=NULL;
  _pQ05=NULL; 
  _pError=NULL;
}
//////////////////////////////////////////////////////////////////
/// \brief Residual error model destructor
//
CResidualErrorModel::~CResidualErrorModel()
{
  delete _pQ95;
  delete _pQ05; 
  delete _pError;
}


void lm(const double *eta,const double *Qtrans,const int N, double &mu0,double &mu1)
{
  //STUB
}
//////////////////////////////////////////////////////////////////
/// \brief Uses method of moments to estimate AR1 coefficients mu0 and mu1, plus autocorrelation coeff rho, sigma_eta, and sigma_y
/// only uses gap-free data 
//
void AR1_MoM(const double *eta,const double *Qtrans, const int N, const meantype mtype,         //inputs
             double &mu0, double &mu1,double &rho,double &sigma, double *mu, double *etastar)   //outputs
{
  double s,sb,sf;
  mu0=mu1=0;
  if      (mtype==MEAN_LINEAR  ) {lm(eta,Qtrans,N,mu0,mu1);} 
  else if (mtype==MEAN_CONSTANT) {for (int n=0;n<N;n++){mu0+=eta[n]/(double)(N);}} 
  else if (mtype==MEAN_ZERO    ) {}//do nothing


  double sum=0.0;
  for (int n=0;n<N;n++){
    mu     [n]=mu0+mu1*Qtrans[n];
    etastar[n]=eta[n]-mu[n];
    sum+=etastar[n]*etastar[n];
  }
  
  rho=sb=sf=0.0;
  for(int n=0;n<N-1;n++) {
    sb+=etastar[n+1];
    sf+=etastar[n];
    rho+=etastar[n+1]*etastar[n];
  }
  s=sqrt(sum/(double)(N));     //sigma_eta
  rho=rho/sb/sf/(double)(N-1); //autocorrelation
  sigma =sqrt(s*s*1-rho*rho);  //sigmaY
}
//////////////////////////////////////////////////////////////////
/// \brief generates time series of output eta using AR1 autocorrelation 
//
void generate_AR1(const double *mu,const int N,const double &sigma,const double &rho,double *eta)
{
  double sd=sigma/sqrt(1.0-rho*rho);
  eta[0] = mu[0] + sd*GaussRandom();
  bool flag = true;
  for (int n=1; n<N; n++){
    if ((mu[n-1]==RAV_BLANK_DATA) || (mu[n]==RAV_BLANK_DATA) ) {
      eta[n] = RAV_BLANK_DATA;
      flag = true;
    } 
   else {
      if (flag) { //last datapoint missing
        eta[n] = mu[n] + sd*GaussRandom();
        flag =false;
      }
      else{
        eta[n] = rho*(eta[n-1]-mu[n-1]) + mu[n] + sigma*GaussRandom();
      }
    }
  }
}
//////////////////////////////////////////////////////////////////
/// \brief calculates residual error model and generates uncertainty quantiles for simulated output 
//
void  CResidualErrorModel::CalculateREM(CTimeSeriesABC  *pTSmod,
                                        CTimeSeriesABC  *pTSObs,
                                        CTimeSeriesABC  *pTSWeights,
                                        const double    &starttime,
                                        const double    &endtime,
                                        const optStruct &Options) const
{
  int    nn;
  int    skip  =0;
  double obsval,modval;
  double lambda=0.2;
  double A=0;
  
  if(!strcmp(pTSObs->GetName().c_str(),"HYDROGRAPH") && (Options.ave_hydrograph == true)) { skip = 1; }
  double dt = Options.timestep;

  int nnstart=pTSObs->GetTimeIndexFromModelTime(starttime)+skip; //works for avg. hydrographs
  int nnend  =pTSObs->GetTimeIndexFromModelTime(endtime  )+1;    //+1 is just because below loops expressed w.r.t N, not N-1

  // Count non-blank observations 
  //-------------------------------------------------------
  int Nobs(0);
  for(nn=nnstart;nn<nnend;nn++)
  {
    obsval=pTSObs->GetSampledValue(nn);
    if (obsval!=RAV_BLANK_DATA){Nobs++;}
  }

  // Calculate transformed flows when data available
  //-------------------------------------------------------
  double mu0,mu1,rho,sigma;
  //double *aErrors=new double [Nobs];
  double *aEta   =new double [Nobs];
  double *aQtrans=new double [Nobs];
  double *aQmod  =new double [Nobs];
  double *mu     =new double [Nobs];
  double *etastar=new double [Nobs];
  int n=0;
  for(nn=nnstart;nn<nnend;nn++)
  {
    obsval=pTSObs->GetSampledValue(nn);
    if (obsval!=RAV_BLANK_DATA)
    {
      modval=pTSmod->GetSampledValue(nn);
      aQmod  [n]=modval;
      //aErrors[n]=obsval-modval; n++;//why not modval-obsval? (not used here)
      aEta   [n]=BoxCoxTransform(obsval,A,lambda)-BoxCoxTransform(modval,A,lambda);
      aQtrans[n]=BoxCoxTransform(modval,A,lambda); 
      n++;
    }
  }

  // Calculate AR1 autocorrelation (rho), mu, and eta* 
  //-------------------------------------------------------
  AR1_MoM(aEta,aQtrans,Nobs,_meanType,  mu0,mu1,rho,sigma,mu,etastar);
  
  //  re-introduce gaps in observed time series
  //-------------------------------------------------------
  int Ntotal=nnend-nnstart; //This has to be the full simulation time 
  double *mu_gapped=new double[Ntotal]; 
  n=0;
  for(int nnn=0;nnn<Ntotal;nnn++)
  {
    mu_gapped[nnn]=RAV_BLANK_DATA;
    obsval=pTSObs->GetSampledValue(nn);
    if (obsval!=RAV_BLANK_DATA){mu_gapped[nnn]=mu[n]; n++;}
  }

  // Generate a set of ensemble predictions from error model   
  // corresponds to calc_pred_reps() routine 
  //-------------------------------------------------------
  int nEnsembleMems=100;
  double **predictions = new double *[nEnsembleMems];
  double *eta_r        = new double  [Ntotal];
  for (int r=0;r<nEnsembleMems;r++){
    generate_AR1(mu_gapped,Ntotal,sigma,rho,eta_r);
    predictions[r]=new double[Ntotal];
    for(int n=0;n<Ntotal;n++) {
      predictions[r][n]=InvBoxCoxTransform(eta_r[n],aQmod[n],A,lambda); //JRC: why is this not aQobs??
    }
  }
  delete [] eta_r;
  delete [] mu_gapped;

  // Calculate quantile bounds on probabilistic hydrographs
  //-------------------------------------------------------
  double *aQ05 =new double [Ntotal];
  double *aQ50 =new double [Ntotal];
  double *aQ95 =new double [Ntotal];
  double *aQobs=new double [Ntotal];
  double *predvec=new double [nEnsembleMems];
  for (int n=0; n<Ntotal; n++){
    for(int r=0;r<nEnsembleMems;r++) {predvec[r]=predictions[r][n];} //vector of all ensemble values at time n
    quickSort(predvec,0,nEnsembleMems-1);
    aQobs[n]=pTSObs->GetSampledValue(nnstart+n);
    aQ05[n]=getPercentileVal(predvec,nEnsembleMems,0.05);
    aQ50[n]=getPercentileVal(predvec,nEnsembleMems,0.50);
    aQ95[n]=getPercentileVal(predvec,nEnsembleMems,0.95);
  }
  delete [] predvec;

  // Calculate sharpness/reliability/CRPS
  //-------------------------------------------------------
  double sharpness  =Sharpness  (aQobs,predictions,Ntotal,nEnsembleMems);
  double CRPSs      =CRPS       (aQobs,predictions,Ntotal,nEnsembleMems);
  double reliability=Reliability(aQobs,predictions,Ntotal,nEnsembleMems);
  //Calculate innovations?? (in residualFunctions.r)


  //memory cleanup
  delete [] aQobs;
  delete [] aEta;
  delete [] aQtrans;
  delete [] aQmod;
  delete [] mu;
  delete [] etastar;
  for(int r=0;r<nEnsembleMems;r++) { delete [] predictions[r];} delete [] predictions;
  delete [] aQ05;
  delete [] aQ50;
  delete [] aQ95;
}
//////////////////////////////////////////////////////////////////
/// \brief calculates residual error model and generates uncertainty quantiles for simulated output 
//
void  CResidualErrorModel:: WriteOutput (const optStruct &Options) const
{
  //for each hydrograph, write single file with time. hour, obs, sim, Q05, Q50, Q95 (or possibly more later)
}