name: RavenHydroFramework Testing

on:
  push:
    branches:
     - main
  pull_request:

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install uncrustify cppcheck iwyu
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  build:
    name: Build RavenHydroFramework binary
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install libnetcdf-dev build-essential cmake
     - name: Fetch NetCDF CMake script
       run: |
         wget https://raw.githubusercontent.com/Kitware/VTK/master/CMake/FindNetCDF.cmake -P cmake
     - name: Build
       run: |
         cmake . -DCMAKE_BUILD_TYPE=Release
         make
     - name: Run tests
       run: |
         ./Raven
         ./Raven -v
