name: RavenHydroFramework Testing

on:
  push:
    branches:
     - main
  pull_request:

jobs:
  lint:
    name: Code Quality Checks
    if: github.event_name != 'push' || github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install uncrustify cppcheck iwyu
      - uses: actions/setup-python@v4
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files

  build:
    name: Build RavenHydroFramework binary (${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    defaults:
      run:
        shell: bash
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install libnetcdf-dev build-essential cmake
     - name: Fetch NetCDF CMake script
       run: |
         wget https://raw.githubusercontent.com/Kitware/VTK/master/CMake/FindNetCDF.cmake -P cmake
     - name: Build
       id: build
       continue-on-error: true
       run: |
         cmake .
         cmake --build . --config ${{ matrix.build_type }}
     - name: Run tests
       if: steps.build.outcome == 'success'
       run: |
         ./Raven
         ./Raven -v
